### ISSUE TITLE
Problem with UTF-8 characters

### ISSUE THREAD

**Issue by urbalazs** [reneeb/otrs-ImportExportDynamicFields#2]
Hi @reneeb
Exporting the dynamic fields works fine, but the importing breaks the descriptions that contain UTF-8 characters. See this screenshot:

![importexportdynamicfields](https://cloud.githubusercontent.com/assets/1006118/19420338/c87cfa3c-93e9-11e6-8b05-84e4b31c51c4.png)

How to reproduce the error:
1. Create some dynamic fields
2. Export
3. Import

**Comment by reneeb** [comment]
Fixed with fb15af2

Version 5.0.3 will be online soon. Thanks for filing the bug!
